services:
  # Server service
  - type: web
    name: my-portfolio-server
    runtime: image
    repo: https://github.com/Manoj-Sunar/My-Portfolio
    plan: free
    dockerContext: .
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  # Client service (updated name)
  - type: web
    name: manoj-portfolio
    runtime: image
    repo: https://github.com/Manoj-Sunar/My-Portfolio
    plan: free
    dockerContext: .
    dockerfilePath: ./client/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://my-portfolio-server.onrender.com