services:
  - type: web
    name: my-portfolio-server
    runtime: docker
    repo: https://github.com/Manoj-Sunar/My-Portfolio
    plan: free
    dockerContext: ./server  # Use server folder as context
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  - type: web
    name: manoj-portfolio
    runtime: docker
    repo: https://github.com/Manoj-Sunar/My-Portfolio
    plan: free
    dockerContext: ./client  # Use client folder as context
    dockerfilePath: ./client/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://my-portfolio-server.onrender.com